plugins:
  needs_love_enabled:
    default: false
    client: true
  needs_love_tag:
    default: "needs-love"
    client: true
  needs_love_allowed_groups:
    default: ""
    type: group_list
    list_type: compact
